# Generated by Django 4.2 on 2023-04-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(help_text='Sex, 1 is man 0 is woman', null=True),
        ),
    ]
