# Generated by Django 4.2 on 2023-04-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_profile_age_weightmeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AlterField(
            model_name='weightmeasurement',
            name='value',
            field=models.IntegerField(help_text='Weight in kg'),
        ),
        migrations.CreateModel(
            name='BodyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
    ]
