# Generated by Django 4.2 on 2023-04-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_remove_profile_age_alter_weightmeasurement_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightmeasurement',
            name='profile',
        ),
        migrations.DeleteModel(
            name='BodyStats',
        ),
        migrations.DeleteModel(
            name='WeightMeasurement',
        ),
    ]
