# Generated by Django 4.2.1 on 2023-05-31 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0002_alter_profile_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exercise name', max_length=50)),
                ('desc', models.CharField(help_text='Exercise description', max_length=250)),
                ('bodypart_a', models.IntegerField(choices=[(0, 'NOSE'), (1, 'LEFT_EYE_INNER'), (2, 'LEFT_EYE'), (3, 'LEFT_EYE_OUTER'), (4, 'RIGHT_EYE_INNER'), (5, 'RIGHT_EYE'), (6, 'RIGHT_EYE_OUTER'), (7, 'LEFT_EAR'), (8, 'RIGHT_EAR'), (10, 'MOUTH_RIGHT'), (11, 'LEFT_SHOULDER'), (12, 'RIGHT_SHOULDER'), (13, 'LEFT_ELBOW'), (14, 'RIGHT_ELBOW'), (15, 'LEFT_WRIST'), (16, 'RIGHT_WRIST'), (17, 'LEFT_PINKY'), (18, 'RIGHT_PINKY'), (19, 'LEFT_INDEX'), (20, 'RIGHT_INDEX'), (21, 'LEFT_THUMB'), (22, 'RIGHT_THUMB'), (23, 'LEFT_HIP'), (24, 'RIGHT_HIP'), (25, 'LEFT_KNEE'), (26, 'RIGHT_KNEE'), (27, 'LEFT_ANKLE'), (28, 'RIGHT_ANKLE'), (29, 'LEFT_HEEL'), (30, 'RIGHT_HEEL'), (31, 'LEFT_FOOT_INDEX'), (32, 'RIGHT_FOOT_INDEX')], help_text='Bodypart A name')),
                ('bodypart_b', models.IntegerField(choices=[(0, 'NOSE'), (1, 'LEFT_EYE_INNER'), (2, 'LEFT_EYE'), (3, 'LEFT_EYE_OUTER'), (4, 'RIGHT_EYE_INNER'), (5, 'RIGHT_EYE'), (6, 'RIGHT_EYE_OUTER'), (7, 'LEFT_EAR'), (8, 'RIGHT_EAR'), (10, 'MOUTH_RIGHT'), (11, 'LEFT_SHOULDER'), (12, 'RIGHT_SHOULDER'), (13, 'LEFT_ELBOW'), (14, 'RIGHT_ELBOW'), (15, 'LEFT_WRIST'), (16, 'RIGHT_WRIST'), (17, 'LEFT_PINKY'), (18, 'RIGHT_PINKY'), (19, 'LEFT_INDEX'), (20, 'RIGHT_INDEX'), (21, 'LEFT_THUMB'), (22, 'RIGHT_THUMB'), (23, 'LEFT_HIP'), (24, 'RIGHT_HIP'), (25, 'LEFT_KNEE'), (26, 'RIGHT_KNEE'), (27, 'LEFT_ANKLE'), (28, 'RIGHT_ANKLE'), (29, 'LEFT_HEEL'), (30, 'RIGHT_HEEL'), (31, 'LEFT_FOOT_INDEX'), (32, 'RIGHT_FOOT_INDEX')], help_text='Bodypart B name')),
                ('bodypart_c', models.IntegerField(choices=[(0, 'NOSE'), (1, 'LEFT_EYE_INNER'), (2, 'LEFT_EYE'), (3, 'LEFT_EYE_OUTER'), (4, 'RIGHT_EYE_INNER'), (5, 'RIGHT_EYE'), (6, 'RIGHT_EYE_OUTER'), (7, 'LEFT_EAR'), (8, 'RIGHT_EAR'), (10, 'MOUTH_RIGHT'), (11, 'LEFT_SHOULDER'), (12, 'RIGHT_SHOULDER'), (13, 'LEFT_ELBOW'), (14, 'RIGHT_ELBOW'), (15, 'LEFT_WRIST'), (16, 'RIGHT_WRIST'), (17, 'LEFT_PINKY'), (18, 'RIGHT_PINKY'), (19, 'LEFT_INDEX'), (20, 'RIGHT_INDEX'), (21, 'LEFT_THUMB'), (22, 'RIGHT_THUMB'), (23, 'LEFT_HIP'), (24, 'RIGHT_HIP'), (25, 'LEFT_KNEE'), (26, 'RIGHT_KNEE'), (27, 'LEFT_ANKLE'), (28, 'RIGHT_ANKLE'), (29, 'LEFT_HEEL'), (30, 'RIGHT_HEEL'), (31, 'LEFT_FOOT_INDEX'), (32, 'RIGHT_FOOT_INDEX')], help_text='Bodypart C name')),
                ('start_angle', models.IntegerField(help_text='Starting angle', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('end_angle', models.IntegerField(help_text='Ending angle', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(help_text='Exercise reps')),
                ('date', models.DateField(help_text='Date of measurement')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
    ]
