# Generated by Django 4.2.1 on 2023-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=1, help_text='Exercise sets'),
        ),
    ]
