# Generated by Django 4.2.1 on 2023-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(help_text='Training date'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=1, help_text='Exercise reps'),
        ),
    ]
